---
title: "trabajo"
author: "Deyner Lopez Pineda Maria Daysi Hadeil"
date: "18/9/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,
                      message = FALSE,
                      warning = FALSE)
```


```{r}
library(knitr)
library(ggplot2)
encuesta <- read.csv2("Encuesta_habitos_dep.csv", 
                       encoding = "UTF-8",
                      header = TRUE,
                       dec = ".")
```


## genero
```{r fig.align='center'}
genero <- table(encuesta$genero)
kable(genero,col.names = c("Genero","Cantidad de Respuestas"))
```

```{r fig.align='center'}
parametros_anterior <- par(no.readonly = TRUE)
#grafica de variable genero

par(bg="white")
plot(seq(0,3, length.out = 132), seq(0,132, length.out = 132), type="n",
     main   = "Género",
     
     font.main = 4,
     font.lab  = 4,
     cex.main  = 1.1,
     cex.lab   = 0.8,
     cex.sub   = 0.8,
     axes      = FALSE,
     xlab      = " ",
     ylab      = "Numero de personas que respondierón ",
     
     )

rect(par("usr")[1],par("usr")[3],par("usr")[2],par("usr")[4],col="white")

abline(h   = seq(0,132,10), 
       col = rep("grey30",17), 
       lty = 3,
       
       )

#mostramos con barplot la tabla1
grafica_genero <- barplot(genero,
                col       = c("blue", "yellow4"),
                font.axis = 2,
                axes      = FALSE,
                add       = TRUE
                )
axis(2, at = c(0,35,70,97,132),las = 1)

text(grafica_genero,
     c(45,105),
     labels = paste(round((genero/sum(genero)*100),1),"%")
     )

par(parametros_anterior)
```
<analisis>

</analisis>

## fecha

```{r}
kable(table(encuesta$edad),col.names = c("Edad","Número de Respuestas"))
```

```{r}
a1 <-table(encuesta$edad)
```

```{r}
b1 <-a1/sum(a1) * 100
```

```{r fig.align='center', fig.height=7, fig.width=15}
parametros_anterior <- par(no.readonly = TRUE)
colores <-c("#0c67da")
b1<- b1[order(b1, decreasing=TRUE)]
ht <- barplot(b1, 
        las = 1, 
        space = 0.2,
        main = "EDAD SEGUN FECHA DE NACIMIENTO",
        density = 50,
        ylab = "Cantidad de personas que respondierón",
        xlab = "Edad (en años)",
        ylim = c(0,21),
         col = 1:dim(b1))
abline(h = seq(0, 20,1 ), col= rep("grey40",8), lty = 3)
text(ht, c (19.70, 18.1, 13.3, 10.1, 9.3,6,6,5.3,2.8,2.8,2.8,2,1.2,1.2,1.2,1.2,1.2,1.2,1.2,1.2) , labels = paste(round(b1,2),"%"))

par(parametros_anterior)

```

<analisis>

</analisis>

## papa

```{r fig.align='center'}
kable(table(encuesta$PAPA),col.names = c("PAPA","Frecuencia"))
```

```{r fig.align='center'}
param_ant <- par(no.readonly = TRUE)
par(mar = param_ant$mar + c(0, 2, 0, 0))
plot(c(3, 5), c(0, 20), type = "n", xlab = "", ylab = "",
     las = 1)
title(main = "Distribución del PAPA",
     xlab = "Promedio Académico Ponderado Acumulado",
     ylab = "Número de estudiantes")
abline(h = seq(0, 20, 2), col = "gray15", lty = 9)
hist(encuesta$PAPA, nclass = 20,
     col = "lightblue",
     add = TRUE)
par(param_ant)
```


<resumen numerico>

</resumen numerico>
```{r}
papa <- as.numeric(encuesta$PAPA_depurado)
tabla_papa <- sort(table(papa), decreasing = TRUE)
j <- cbind(papa)
k <- summary(papa)
k

```


<analisis>

</analisis>

## estrato


```{r fig.align='center'}
estrato_tabla <- table(encuesta$estrato_depurado)
kable(estrato_tabla,col.names = c("Estrato","Respuestas"))
```

```{r fig.align='center'}
estrato <- as.numeric(encuesta$estrato_depurado)
tabla_estrato <- sort(table(estrato), decreasing = TRUE)
parametros_anterior <- par(no.readonly = TRUE)



par(bg = "white")

hist(estrato, main = "estrato",
     xlab = "estrato", ylab = "Frecuencia",
     border = "black",
     col = "wheat",
     las =1,
     xlim = c(0,5))

par(parametros_anterior)

```

```{r}
j <- cbind(estrato)
k <- summary(estrato)
k
```
<resuemn numerico>

</resumen numerico>

<analisis>

</analisis>


## computador mesa

```{r fig.align='center'}
computador_Mesa <- table(encuesta$computador_mesa)
kable(computador_Mesa,col.names = c("Repuesta","Cantidad de Respuestas"))
```


```{r fig.align='center'}
parametros_anterior <- par(no.readonly = TRUE)

par(bg="white")

plot(seq(0,10, length.out = 60), seq(0,6, length.out = 60), type="n",
     main   = "Computador de mesa",
     
     font.main = 4,
     font.lab  = 4,
     cex.main  = 1.1,
     cex.lab   = 0.8,
     cex.sub   = 0.8,
     axes      = FALSE,
     xlab      = " ",
     ylab      = "Numero de personas que respondierón ",
     xlim = c(0,5),
     ylim = c(0,100)
     )

rect(par("usr")[1],par("usr")[3],par("usr")[2],par("usr")[4],col="white")

abline(h   = seq(0,100,10), 
       col = rep("grey30",17), 
       lty = 3,
       
       )

Barras_computador <- barplot(computador_Mesa,
                col       = c("blue", "yellow4"),
                font.axis = 2,
                axes      = FALSE,
                add       = TRUE,
                xlim = c(0,5),
                names.arg = ""
                )
axis(2, at = c(),las = 1)

text(Barras_computador,
     c(96,7,5,42),
     labels = paste(round((computador_Mesa/sum(computador_Mesa)*100),1),"%")
     )

text(Barras_computador+0.1,
     par("usr")[3],0.4,
     labels = c("No","Si,pero prestado","Si, pero alquilado","Si, Propio"),
     srt = 45,
     pos = 2,
     xpd = TRUE)

par(parametros_anterior)
```

<analisis>

</analisis>


## portatil
```{r fig.align='center'}
Portatil <- table(encuesta$portatil)
```

```{r fig.align='center'}
kable(Portatil,col.names = c("Respuesta","Cantidad de respuestas"))
```

```{r fig.align='center'}
parametros_anterior <- par(no.readonly = TRUE)
#Grafica variable portatil

par(bg = "white")
plot(seq(0,10, length.out = 60), seq(0,6, length.out = 60), type="n",
     main   = "Portatil",
     
     font.main = 4,
     font.lab  = 4,
     cex.main  = 1.1,
     cex.lab   = 0.8,
     cex.sub   = 0.8,
     axes      = FALSE,
     xlab      = " ",
     ylab      = "Numero de personas que respondierón ",
     xlim = c(0,5),
     ylim = c(0,100)
     )

rect(par("usr")[1],par("usr")[3],par("usr")[2],par("usr")[4],col="white")

abline(h   = seq(0,100,10), 
       col = rep("grey30",17), 
       lty = 3,
       
       )


Barras_Portatil <- barplot(Portatil,
                           col       = c("firebrick2", "olivedrab3", "yellow4", "steelblue"),
                font.axis = 2,
                axes      = FALSE,
                add       = TRUE,
                xlim = c(0,5),
                names.arg = ""
                )
axis(2, at = c(),las = 1)

text(Barras_Portatil,
     c(21,7,20,100),
     labels = paste(round((Portatil/sum(Portatil)*100),1),"%")
     )

text(Barras_Portatil+0.1,
     par("usr")[3],0.4,
     labels = c("No","Si,pero alquilado","Si, pero prestado","Si, Propio"),
     srt = 45,
     pos = 2,
     xpd = TRUE)

par(parametros_anterior)

```

<analisis>

</analisis>

## internet
```{r fig.align='center'}
internet <- table(encuesta$internet)
```

```{r fig.align='center'}
kable(internet,col.names = c("Respuestas","Cantidad de respuestas"))
```

```{r fig.align='center'}
parametros_anterior <- par(no.readonly = TRUE)
#Grafica variable internet

par(bg = "white")
plot(seq(0,10, length.out = 60), seq(0,6, length.out = 60), type="n",
     main   = "Internet",
     
     font.main = 4,
     font.lab  = 4,
     cex.main  = 1.1,
     cex.lab   = 0.8,
     cex.sub   = 0.8,
     axes      = FALSE,
     xlab      = " ",
     ylab      = "Numero de personas que respondierón ",
     xlim = c(0,7),
     ylim = c(0,80)
     )

rect(par("usr")[1],par("usr")[3],par("usr")[2],par("usr")[4],col="white")

abline(h   = seq(0,100,10), 
       col = rep("grey30",17), 
       lty = 3,
       
       )


Barras_internet <- barplot(internet,
                           col       = c("firebrick2", "olivedrab3", "yellow4", "steelblue", "tomato3", "springgreen3"),
                font.axis = 2,
                axes      = FALSE,
                add       = TRUE,
                xlim = c(0,5),
                names.arg = ""
                )
axis(2, at = c(),las = 1)

text(Barras_internet,
     c(9, 4, 7, 8, 48, 75),
     labels = paste(round((internet/sum(internet)*100),1),"%")
     )

text(Barras_internet+0.1,
     par("usr")[3],0.4,
     labels = c("Si, pero alquilado", "si, de contrabando","Si, plan datos ","Si, pero prestado", "Si, propio", "Si, familiar"),
     srt = 45,
     pos = 2,
     xpd = TRUE)

par(parametros_anterior)

```

<analisis>

</analisis>


## smartphone
```{r fig.align='center'}
Smartphone <- table(encuesta$smartphone)
```

```{r fig.align='center'}
kable(Smartphone,col.names = c("Repsuesta","cantidad de respuestas"))
```

```{r fig.align='center'}
parametros_anterior <- par(no.readonly = TRUE)
#Grafica variable Smartphone

par(bg = "white")
plot(seq(0,10, length.out = 60), seq(0,6, length.out = 60), type="n",
     main   = "Smartphone",
     
     font.main = 4,
     font.lab  = 4,
     cex.main  = 1.1,
     cex.lab   = 0.8,
     cex.sub   = 0.8,
     axes      = FALSE,
     xlab      = " ",
     ylab      = "Numero de personas que respondierón ",
     xlim = c(0,6),
     ylim = c(0,140)
     )

rect(par("usr")[1],par("usr")[3],par("usr")[2],par("usr")[4],col="white")

abline(h   = seq(0,140,20), 
       col = rep("grey30",17), 
       lty = 3,
       
       )


Barras_smartphone <- barplot(Smartphone,
                           col       = c("firebrick2", "olivedrab3", "yellow4", "steelblue"),
                font.axis = 2,
                axes      = FALSE,
                add       = TRUE,
                xlim = c(0,5),
                names.arg = ""
                )
axis(2, at = c(),las = 1)

text(Barras_smartphone,
     c(5, 5, 5, 7, 133),
     labels = paste(round((Smartphone/sum(Smartphone)*100),1),"%")
     )

text(Barras_smartphone+0.1,
     par("usr")[3],0.4,
     labels = c("No Respondio", "NO", "Si, pero alquilado", "Si, pero prestado ","Si, propio"),
     srt = 45,
     pos = 2,
     xpd = TRUE)
par(parametros_anterior)

```

<analisis>

</analisis>

## estad_gov

```{r fig.align='center'}
Estado_gov <- table(encuesta$estad_gov)
```

```{r fig.align='center'}
kable(Estado_gov,col.names = c("Respuesta","Número de Respuestas"))
```

```{r fig.align='center'}
parametros_anterior <- par(no.readonly = TRUE)
#Grafica variable Estado gov

par(bg = "white")
plot(seq(0,10, length.out = 60), seq(0,6, length.out = 60), type="n",
     main   = "Estado Gov",
     
     font.main = 4,
     font.lab  = 4,
     cex.main  = 1.1,
     cex.lab   = 0.8,
     cex.sub   = 0.8,
     axes      = FALSE,
     xlab      = " ",
     ylab      = "Numero de personas que respondierón ",
     xlim = c(0,4),
     ylim = c(0,100)
     )

rect(par("usr")[1],par("usr")[3],par("usr")[2],par("usr")[4],col="white")

abline(h   = seq(0,100,10), 
       col = rep("grey30",17), 
       lty = 3,
       
       )

Barras_Estado <- barplot(Estado_gov,
                           col = c("olivedrab3", "yellow4"),
                font.axis = 2,
                axes      = FALSE,
                add       = TRUE,
                xlim = c(0,5),
                names.arg = ""
                )
axis(2, at = c(),las = 1)

text(Barras_Estado,
     c(5, 5),
     labels = paste(round((Estado_gov/sum(Estado_gov)*100),1),"%")
     )

text(Barras_Estado+0.1,
     par("usr")[3],0.4,
     labels = c("No", "No respindio", "si"),
     srt = 45,
     pos = 2,
     xpd = TRUE)

par(parametros_anterior)

```


<analisis>

</analisis>

## origen covid

```{r fig.align='center'}
Origen_depurado <- with(encuesta, c(Origen1, Origen2, Origen3))
origen <- sort(table(Origen_depurado), decreasing = TRUE)
```

```{r fig.align='center'}
kable(origen,col.names = c("Origen","Respuestas"))
```

```{r fig.align='center'}
#Grafica variable Origen covid 19

parametros_anterior <- par(no.readonly = TRUE)

par(bg = "white")
plot(seq(0,10, length.out = 60), seq(0,6, length.out = 60), type="n",
     main   = "Origen covid 19",
     
     font.main = 4,
     font.lab  = 4,
     cex.main  = 1.1,
     cex.lab   = 0.8,
     cex.sub   = 0.8,
     axes      = FALSE,
     xlab      = " ",
     ylab      = "Numero de personas que respondierón ",
     xlim = c(0,6),
     ylim = c(0,80)
     )

rect(par("usr")[1],par("usr")[3],par("usr")[2],par("usr")[4],col="white")

abline(h   = seq(0,80,10), 
       col = rep("grey30",17), 
       lty = 3
       )

Barras_origen <- barplot(origen,
                           col = c("turquoise2", "violet", "lawngreen", "lightpink1", "orange"),
                font.axis = 2,
                axes      = FALSE,
                add       = TRUE,
                xlim = c(0,5),
                names.arg = ""
                )
axis(2, at = c(),las = 1)

text(Barras_origen,
     c(77, 50, 18, 11, 6),
     labels = paste(round((origen/sum(origen)*100),1),"%")
     )

text(Barras_origen+0.1,
     par("usr")[3],0.4,
     labels = "",
     srt = 45,
     pos = 2,
     xpd = TRUE)

legend(Barras_origen[2, 1] +1 , 80, legend = c("Fue un resultado de pasar el virus 
de animales a los humanos ",
" Fue fabricado en un laboratorio ", 
"No respondio",
"Es una conspiración",
"No es real, es un pretexto de
los gobiernos del mundo"),
       col = c("turquoise2", "violet", "lawngreen", "lightpink1", "orange"),
       pch = 17)

par(parametros_anterior)
```

<analisis>

</analisis>

## habitos

```{r fig.align='center'}
combinar<- with(encuesta, c(habito_1,habito_2,habito_3,habito_4
                          ,habito_5,habito_6,habito_7,habito_8,habito_9
                          ,habito_10,habito_11,habito_12,habito_13,habito_14
                          ,habito_15,habito_16,habito_17))

tabla <- sort(table(combinar))
kable(tabla,col.names = c("Habito","Número de respuestas"))

```

```{r fig.align='center'}

par(mar=c(4,23.9,1,1))
graficaber <-barplot(tabla, las = 2, cex.names = 0.7,cex.axis = 1,horiz = TRUE,xlim = c(0,130),
                     col = c("cyan","darkred","blue","yellow","violet","tomato"))

text(c(25,34,35,44,50,55,55,60,60,68,68,70,78,80,85,85,91,93,105,108,113)+1,graficaber,
     labels = paste(round(tabla/sum(tabla)*100,2),"%")
     )


```

<analisis>

</analisis>

## aleatorio

```{r fig.align='center'}
tabla9<- sort(table(encuesta$aleatorio))
kable(tabla9,col.names = c("Valor Aleatorio","Frecuencia"))
```

```{r fig.align='center'}
grafica9<-barplot(tabla9,las=2,col = c("cyan","darkred","blue","yellow","violet","tomato"),ylim = c(0,40))

text(grafica9,
     c(3,8,10,10,11,12,12,15,16,21,36),
     labels = paste(round((tabla9/sum(tabla9)*100),1),"%")
     )
```


<analisis>

</analisis>

## papa + genero

```{r fig.align='center'}
ggplot(encuesta, aes(genero,PAPA,col = genero)) +
  geom_point(size = 2) +
  geom_smooth(se = FALSE)
```

<analisis>

</analisis>

## papa + edad

```{r,fig.height=7, fig.width=9,fig.align='center'}
ggplot(encuesta ,aes(x=edad,y=PAPA,col=PAPA))+
  geom_point(size = 2)+theme(axis.text.x = element_text(angle = 90, hjust = 1))

```

## papa + carrera

```{r fig.align='center'}
ggplot(encuesta, aes(PAPA, Carrera_depurada,col = Carrera_depurada)) +
  geom_point(size = 2) +
  geom_smooth(se = FALSE)
```

<analisis>

</analisis>

## papa + estrato
```{r fig.align='center'}
ggplot(encuesta, aes(PAPA, estrato,col = PAPA)) +
  geom_point(size = 2) +
  geom_smooth(se = FALSE)
```


<analisis>

</analisis>
## Papa + computador mesa

```{r fig.align='center'}
Computador_mesa1 <- tapply(encuesta$PAPA_depurado, encuesta$computador_mesa, mean, na.rm = TRUE)
```


```{r fig.height=7, fig.width=8,fig.align='center'}
parametros_anterior <- par(no.readonly = TRUE)

par(mar = parametros_anterior$mar + c(16, 10, 0, 0),
    las = 2,
    xaxt = "n",
    yaxt = "n")

with(encuesta, boxplot(PAPA_depurado ~ computador_mesa,
                       xlab = "",
                       notch = TRUE,
                       varwidth = TRUE,
                       col = c("red", "green", "yellow", "orange")))
     

title(main = "PAPA con computador de mesa ")

text(1:length(Computador_mesa1),
     par("usr")[3] - 0.2,
     labels = names(Computador_mesa1),
     srt = 45,
     pos = 2,
     xpd = TRUE)

text(par("usr")[1] - 0.4,
     seq(3, max(encuesta$PAPA_depurado, na.rm = TRUE), 
         0.2),
     labels = formatC(seq(3, max(encuesta$PAPA_depurado, na.rm = TRUE), 0.2),
                      digits = 1,
                      width = 3,
                      format = "f",
                      flag = "0"),
     xpd = TRUE)

axis(side = 2, 
     at = seq(3, max(encuesta$PAPA_depurado, na.rm = TRUE), 0.2))

mtext("computador de mesa", 
      las = 1, 
      side = 1, line = 8)
abline(h = mean(encuesta$PAPA_depurado, na.rm = TRUE),
       col = "blue")

par(parametros_anterior)
```

<analisis>

</analisis>

## Papa + portatil

```{r fig.align='center'}
portatil1 <- tapply(encuesta$PAPA_depurado, encuesta$portatil, mean, na.rm = TRUE)
```


```{r fig.height=7, fig.width=8,fig.align='center'}
parametros_anterior <- par(no.readonly = TRUE)

par(mar = parametros_anterior$mar + c(16, 10, 0, 0),
    las = 2,
    xaxt = "n",
    yaxt = "n")

with(encuesta, boxplot(PAPA_depurado ~ portatil,
                       xlab = "",
                       notch = TRUE,
                       varwidth = TRUE,
                       col = c("red", "green", "yellow", "orange")))
     

title(main = "PAPA con la variable Portatil")

text(1:length(portatil1),
     par("usr")[3] - 0.2,
     labels = names(portatil1),
     srt = 45,
     pos = 2,
     xpd = TRUE)

text(par("usr")[1] - 0.4,
     seq(3, max(encuesta$PAPA_depurado, na.rm = TRUE), 
         0.2),
     labels = formatC(seq(3, max(encuesta$PAPA_depurado, na.rm = TRUE), 0.2),
                      digits = 1,
                      width = 3,
                      format = "f",
                      flag = "0"),
     xpd = TRUE)

axis(side = 2, 
     at = seq(3, max(encuesta$PAPA_depurado, na.rm = TRUE), 0.2))

mtext("portatil", 
      las = 1, 
      side = 1, line = 8)
abline(h = mean(encuesta$PAPA_depurado, na.rm = TRUE),
       col = "blue")

par(parametros_anterior)
```

<analisis>

</analisis>

## Papa + internet

```{r fig.align='center'}
Internet1 <- tapply(encuesta$PAPA_depurado, encuesta$internet, mean, na.rm = TRUE)
```


```{r fig.height=7, fig.width=8, fig.align='center'}
parametros_anterior <- par(no.readonly = TRUE)

par(mar = parametros_anterior$mar + c(16, 10, 0, 0),
    las = 2,
    xaxt = "n",
    yaxt = "n")

with(encuesta, boxplot(PAPA_depurado ~ internet,
                       xlab = "",
                       notch = TRUE,
                       varwidth = TRUE,
                       col = c("red", "green", "yellow", "orange")))
     

title(main = "PAPA con la variable internet")

text(1:length(Internet1),
     par("usr")[3] - 0.2,
     labels = names(Internet1),
     srt = 45,
     pos = 2,
     xpd = TRUE)

text(par("usr")[1] - 0.4,
     seq(3, max(encuesta$PAPA_depurado, na.rm = TRUE), 
         0.2),
     labels = formatC(seq(3, max(encuesta$PAPA_depurado, na.rm = TRUE), 0.2),
                      digits = 1,
                      width = 3,
                      format = "f",
                      flag = "0"),
     xpd = TRUE)

axis(side = 2, 
     at = seq(3, max(encuesta$PAPA_depurado, na.rm = TRUE), 0.2))

mtext("INTERNET", 
      las = 1, 
      side = 1, line = 8)
abline(h = mean(encuesta$PAPA_depurado, na.rm = TRUE),
       col = "blue")

par(parametros_anterior)
```

<analisis>

</analisis>

## Papa + Smartphone

```{r fig.align='center'}
smartphone1 <- tapply(encuesta$PAPA_depurado, encuesta$smartphone, mean, na.rm = TRUE)
```


```{r fig.height=7, fig.width=8, fig.align='center'}
parametros_anterior <- par(no.readonly = TRUE)

par(mar = parametros_anterior$mar + c(16, 10, 0, 0),
    las = 2,
    xaxt = "n",
    yaxt = "n")

with(encuesta, boxplot(PAPA_depurado ~ smartphone,
                       xlab = "",
                       notch = TRUE,
                       varwidth = TRUE,
                       col = c("red", "green", "yellow", "orange")))
     

title(main = "PAPA la variable smartphone ")

text(1:length(smartphone1),
     par("usr")[3] - 0.2,
     labels = names(smartphone1),
     srt = 45,
     pos = 2,
     xpd = TRUE)

text(par("usr")[1] - 0.4,
     seq(3, max(encuesta$PAPA_depurado, na.rm = TRUE), 
         0.2),
     labels = formatC(seq(3, max(encuesta$PAPA_depurado, na.rm = TRUE), 0.2),
                      digits = 1,
                      width = 3,
                      format = "f",
                      flag = "0"),
     xpd = TRUE)

axis(side = 2, 
     at = seq(3, max(encuesta$PAPA_depurado, na.rm = TRUE), 0.2))

mtext("smartphone", 
      las = 1, 
      side = 1, line = 8)
abline(h = mean(encuesta$PAPA_depurado, na.rm = TRUE),
       col = "blue")

par(parametros_anterior)
```
<analisis>

</analisis>







