---
title: "trabajo"
author: "Deyner Lopez Pineda"
date: "18/9/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,
                      message = FALSE,
                      warning = FALSE)
```


```{r}
library(knitr)
encuesta <- read.csv2("Encuesta_habitos_dep.csv", 
                       encoding = "UTF-8",
                       dec = ".")
```

```{r fig.align='center'}
#grafica de variable genero

par(bg="white")
plot(seq(0,3, length.out = 132), seq(0,132, length.out = 132), type="n",
     main   = "Género",
     
     font.main = 4,
     font.lab  = 4,
     cex.main  = 1.1,
     cex.lab   = 0.8,
     cex.sub   = 0.8,
     axes      = FALSE,
     xlab      = " ",
     ylab      = "Numero de personas que respondierón ",
     
     )

rect(par("usr")[1],par("usr")[3],par("usr")[2],par("usr")[4],col="white")

abline(h   = seq(0,132,10), 
       col = rep("grey30",17), 
       lty = 3,
       
       )

#guardar los datos de la columna en una tabla
genero <- table(encuesta$genero)

#mostramos con barplot la tabla1
grafica_genero <- barplot(genero,
                col       = c("blue", "yellow4"),
                font.axis = 2,
                axes      = FALSE,
                add       = TRUE
                )
axis(2, at = c(0,35,70,97,132),las = 1)

text(grafica_genero,
     c(45,105),
     labels = paste(round((genero/sum(genero)*100),1),"%")
     )
```

```{r fig.align='center'}
kable(genero,col.names = c("Genero","Cantidad de Respuestas"))
```


```{r fig.align='center'}
param_ant <- par(no.readonly = TRUE)
par(mar = param_ant$mar + c(0, 2, 0, 0))
plot(c(3, 5), c(0, 20), type = "n", xlab = "", ylab = "",
     las = 1)
title(main = "Distribución del PAPA",
     xlab = "Promedio Académico Ponderado Acumulado",
     ylab = "Número de estudiantes")
abline(h = seq(0, 20, 2), col = "gray15", lty = 9)
hist(encuesta$PAPA, nclass = 20,
     col = "lightblue",
     add = TRUE)
par(param_ant)
```
```{r fig.align='center'}
kable(table(encuesta$PAPA),col.names = c("PAPA","Frecuencia"))
```

```{r fig.align='center'}


par(bg="white")
plot(seq(0,10, length.out = 60), seq(0,6, length.out = 60), type="n",
     main   = "Estrato",
     
     font.main = 4,
     font.lab  = 4,
     cex.main  = 1.1,
     cex.lab   = 0.8,
     cex.sub   = 0.8,
     axes      = FALSE,
     xlab      = " ",
     ylab      = "Numero de personas que respondierón ",
     xlim = c(0,7),
     ylim = c(0,70)
     )

rect(par("usr")[1],par("usr")[3],par("usr")[2],par("usr")[4],col="white")

abline(h   = seq(0,60,10), 
       col = rep("grey30",17), 
       lty = 3,
       
       )

#guardar los datos de la columna en una tabla
estrato <- table(encuesta$estrato)

#mostramos con barplot la tabla1
Barras_estrato <- barplot(estrato,
                col       = c("blue", "yellow4"),
                font.axis = 2,
                axes      = FALSE,
                add       = TRUE,
                xlim = c(0,5)
                )
axis(2, at = c(),las = 1)

text(Barras_estrato,
     c(4,23,48,63,12),
     labels = paste(round((estrato/sum(estrato)*100),1),"%")
     )

```


```{r fig.align='center'}
kable(estrato,col.names = c("Estrato","Respuestas"))
```

```{r fig.align='center'}
par(bg="white")
plot(seq(0,10, length.out = 60), seq(0,6, length.out = 60), type="n",
     main   = "Computador de mesa",
     
     font.main = 4,
     font.lab  = 4,
     cex.main  = 1.1,
     cex.lab   = 0.8,
     cex.sub   = 0.8,
     axes      = FALSE,
     xlab      = " ",
     ylab      = "Numero de personas que respondierón ",
     xlim = c(0,5),
     ylim = c(0,100)
     )

rect(par("usr")[1],par("usr")[3],par("usr")[2],par("usr")[4],col="white")

abline(h   = seq(0,100,10), 
       col = rep("grey30",17), 
       lty = 3,
       
       )

#guardar los datos de la columna en una tabla
computador_Mesa <- table(encuesta$computador_mesa)

#mostramos con barplot la tabla1
Barras_computador <- barplot(computador_Mesa,
                col       = c("blue", "yellow4"),
                font.axis = 2,
                axes      = FALSE,
                add       = TRUE,
                xlim = c(0,5),
                names.arg = ""
                )
axis(2, at = c(),las = 1)

text(Barras_estrato,
     c(96,7,5,42),
     labels = paste(round((computador_Mesa/sum(computador_Mesa)*100),1),"%")
     )

text(Barras_computador+0.1,
     par("usr")[3],0.4,
     labels = c("No","Si,pero prestado","Si, pero alquilado","Si, Propio"),
     srt = 45,
     pos = 2,
     xpd = TRUE)
```
```{r fig.align='center'}
kable(computador_Mesa,col.names = c("Repuesta","Cantidad de Respuestas"))
```



```{r fig.align='center'}
#Grafica variable portatil

par(bg = "white")
plot(seq(0,10, length.out = 60), seq(0,6, length.out = 60), type="n",
     main   = "Portatil",
     
     font.main = 4,
     font.lab  = 4,
     cex.main  = 1.1,
     cex.lab   = 0.8,
     cex.sub   = 0.8,
     axes      = FALSE,
     xlab      = " ",
     ylab      = "Numero de personas que respondierón ",
     xlim = c(0,5),
     ylim = c(0,100)
     )

rect(par("usr")[1],par("usr")[3],par("usr")[2],par("usr")[4],col="white")

abline(h   = seq(0,100,10), 
       col = rep("grey30",17), 
       lty = 3,
       
       )


Portatil <- table(encuesta$portatil)

Barras_Portatil <- barplot(Portatil,
                           col       = c("firebrick2", "olivedrab3", "yellow4", "steelblue"),
                font.axis = 2,
                axes      = FALSE,
                add       = TRUE,
                xlim = c(0,5),
                names.arg = ""
                )
axis(2, at = c(),las = 1)

text(Barras_Portatil,
     c(21,7,20,100),
     labels = paste(round((Portatil/sum(Portatil)*100),1),"%")
     )

text(Barras_Portatil+0.1,
     par("usr")[3],0.4,
     labels = c("No","Si,pero alquilado","Si, pero prestado","Si, Propio"),
     srt = 45,
     pos = 2,
     xpd = TRUE)

```
```{r fig.align='center'}
kable(Portatil,col.names = c("Respuesta","Cantidad de respuestas"))
```


```{r fig.align='center'}
#Grafica variable internet

par(bg = "white")
plot(seq(0,10, length.out = 60), seq(0,6, length.out = 60), type="n",
     main   = "Internet",
     
     font.main = 4,
     font.lab  = 4,
     cex.main  = 1.1,
     cex.lab   = 0.8,
     cex.sub   = 0.8,
     axes      = FALSE,
     xlab      = " ",
     ylab      = "Numero de personas que respondierón ",
     xlim = c(0,7),
     ylim = c(0,80)
     )

rect(par("usr")[1],par("usr")[3],par("usr")[2],par("usr")[4],col="white")

abline(h   = seq(0,100,10), 
       col = rep("grey30",17), 
       lty = 3,
       
       )

internet <- table(encuesta$internet)

Barras_internet <- barplot(internet,
                           col       = c("firebrick2", "olivedrab3", "yellow4", "steelblue", "tomato3", "springgreen3"),
                font.axis = 2,
                axes      = FALSE,
                add       = TRUE,
                xlim = c(0,5),
                names.arg = ""
                )
axis(2, at = c(),las = 1)

text(Barras_internet,
     c(9, 4, 7, 8, 48, 75),
     labels = paste(round((internet/sum(internet)*100),1),"%")
     )

text(Barras_internet+0.1,
     par("usr")[3],0.4,
     labels = c("Si, pero alquilado", "si, de contrabando","Si, plan datos ","Si, pero prestado", "Si, propio", "Si, familiar"),
     srt = 45,
     pos = 2,
     xpd = TRUE)

```
```{r fig.align='center'}
kable(internet,col.names = c("Respuestas","Cantidad de respuestas"))
```


```{r fig.align='center'}
#Grafica variable Smartphone

par(bg = "white")
plot(seq(0,10, length.out = 60), seq(0,6, length.out = 60), type="n",
     main   = "Smartphone",
     
     font.main = 4,
     font.lab  = 4,
     cex.main  = 1.1,
     cex.lab   = 0.8,
     cex.sub   = 0.8,
     axes      = FALSE,
     xlab      = " ",
     ylab      = "Numero de personas que respondierón ",
     xlim = c(0,5),
     ylim = c(0,140)
     )

rect(par("usr")[1],par("usr")[3],par("usr")[2],par("usr")[4],col="white")

abline(h   = seq(0,140,20), 
       col = rep("grey30",17), 
       lty = 3,
       
       )

Smartphone <- table(encuesta$smartphone)

Barras_smartphone <- barplot(Smartphone,
                           col       = c("firebrick2", "olivedrab3", "yellow4", "steelblue"),
                font.axis = 2,
                axes      = FALSE,
                add       = TRUE,
                xlim = c(0,5),
                names.arg = ""
                )
axis(2, at = c(),las = 1)

text(Barras_smartphone,
     c(5, 5, 7, 133),
     labels = paste(round((Smartphone/sum(Smartphone)*100),1),"%")
     )

text(Barras_smartphone+0.1,
     par("usr")[3],0.4,
     labels = c("No", "Si, pero alquilado", "Si, pero prestado ","Si, propio"),
     srt = 45,
     pos = 2,
     xpd = TRUE)


```
```{r fig.align='center'}
kable(Smartphone,col.names = c("Repsuesta","cantidad de respuestas"))
```


```{r fig.align='center'}
combinar<- with(encuesta, c(habito_1,habito_2,habito_3,habito_4
                          ,habito_5,habito_6,habito_7,habito_8,habito_9
                          ,habito_10,habito_11,habito_12,habito_13,habito_14
                          ,habito_15,habito_16,habito_17))

tabla <- sort(table(combinar))
par(mar=c(4,23.9,1,1))
graficaber <-barplot(tabla, las = 2, cex.names = 0.7,cex.axis = 1,horiz = TRUE,xlim = c(0,130),
                     col = c("cyan","darkred","blue","yellow","violet","tomato"))

text(c(25,34,35,44,50,55,55,60,60,68,68,70,78,80,85,85,91,93,105,108,113)+1,graficaber,
     labels = paste(round(tabla/sum(tabla)*100,2),"%")
     )


```

```{r fig.align='center'}
kable(tabla,col.names = c("Habito","Número de respuestas"))
```


```{r fig.align='center'}
tabla9<- sort(table(encuesta$aleatorio))
grafica9<-barplot(tabla9,las=2)


```


```{r fig.align='center'}
#falta reemplazar el primer valor, ya que no recuerdo por cual se debe cambiar, tambien se puede hacer en la base de datos directamente.
kable(tabla9,col.names = c("Número","Cantidad de apariciones"))
```
```{r fig.align='center'}
#relacionar papa con las variables
#Deyner:

#Género (Listo)
#Fecha nacimiento
#Carrera
#Estrato (Listo)
library(ggplot2)
ggplot(encuesta, aes(PAPA, estrato,col = PAPA)) +
  geom_point(size = 2) +
  geom_smooth(se = FALSE)
```


```{r fig.align='center'}
ggplot(encuesta, aes(PAPA, genero,col = genero)) +
  geom_point(size = 2) +
  geom_smooth(se = FALSE)
```

```{r,fig.height=10, fig.width=20,fig.align='center'}
ggplot(encuesta ,aes(x=Fecha_depurada,y=PAPA))+
  geom_point(size = 1)+theme(axis.text.x = element_text(angle = 90, hjust = 1))

```


```{r fig.align='center'}
kable(sort(table(encuesta$Fecha_depurada)),descreasing=FALSE,col.names = c("Fecha","Cantidad de respuestas"))
```



```{r fig.align='center'}
ggplot(encuesta, aes(PAPA, Carrera_depurada,col = Carrera_depurada)) +
  geom_point(size = 2) +
  geom_smooth(se = FALSE)
```

```{r fig.align='center'}
kable(table(encuesta$Carrera_depurada),col.names = c("Carrera","Cantidad de estudiantes por carrera"))
```






